#!/bin/bash

set -e

# Initialize value stored in a file
DUCKDNS_TOKEN="$(< "${DUCKDNS_TOKEN_FILE}")"

cd /dehydrated

sudo -u nobody \
	DUCKDNS_TOKEN="${DUCKDNS_TOKEN}" \
	./dehydrated --register --accept-terms

if [ -n "${DOMAIN}" ]; then
	sudo -u nobody \
		DUCKDNS_TOKEN="${DUCKDNS_TOKEN}" \
		./dehydrated -c -t dns-01 -k hooks/duckdns/hook.sh -d "${DOMAIN}"
else
	sudo -u nobody \
		DUCKDNS_TOKEN="${DUCKDNS_TOKEN}" \
		./dehydrated -c -t dns-01 -k hooks/duckdns/hook.sh
fi

